### ISSUE TITLE
No longer backwards Z

### ISSUE THREAD

**Issue by em** [tmpvar/text2gcode#1]
I fixed this. Z- is towards bed in gcanvas now. You can remove that note.

**Comment by tmpvar** [comment]
Well, either way _should_ work and there really shouldn't be a problem running it on a machine that is oriented with Z+ towards the work.  I believe gcanvas can handle either, right? 

This is definitely not a slight at you, just saying people's machine orientation may differ from ours - My first machine was Z+!

**Comment by em** [comment]
Oh no. Just had more people be confused by it. As you said, it's pretty much standard for Z- to be towards the work. Most commercial CNC machines, and LinuxCNC all use it.

**Comment by em** [comment]
I think we also need another tool that could be put into pipelines for any kind of transformation on raw Gcode.
 Something like 'gpp':
`generator | gpp --rotate 10 --scale 2 --translate 100,200 --mirror z | cnc`

I like this better than adding a --mirror option to Gcanvas and svg2gcode + every other generator.

**Comment by tmpvar** [comment]
I agree; at that point we need a proper gcode parser

**Comment by tmpvar** [comment]
all of my gcode goes through this (which may or may not be a decent starting point)

``` javascript

#!/usr/bin/env node

var split = require('split');
var argv = require('optimist').argv;

process.stdin.once('data', function() {});

var x = argv.x || 0,
    y = argv.y || 0,
    z = argv.z || 0;


process.stdin.pipe(split()).on('data', function(line) {
  line = line.replace(/N[\d]+ /, '');

  if (line[0] === 'T' ||
      line[0] === '/' ||
      line[0] === '(' ||
      line[0] === '%' ||
      line[0] === 'M' ||
      line[0] === 'S')
  {
    return;
  }

  if (line.indexOf('G53') > -1 || line.indexOf('G57') > -1 || line.indexOf('G28') > -1 || line.indexOf('G43') > -1) {
    return;
  }


  line = line.replace(/G1F/, 'F');
  line = line.replace(/\.(\d\d)\d\d/g, '.$1')

  console.log(line);
});

console.log([
  '$H',
  'M4 S' + (argv.s || 10000),
  'G4 P' + (argv.p || 10),
  'G10 L20 P1 X0 Y0 Z0',
  'G21G17',
  'G1 X' + x + ' Y' + y + ' F' + (argv.f || 4000),
  'G1 Z' + z,
  'G10 L20 P1 X0 Y0 Z0',
  'G28.1 X0 Y0 Z0',
  'G1 Z5'  // raise the tool before dragging it across the work!
].join('\n'))


process.stdin.once('end', function() {
  console.log('G1 Z' + (Math.abs(z) || 5));
  console.log('G4 P2');
  console.log('M5')

  if (!argv.nohome) {
    console.log('$H');
    console.log('G10 L20 P1 X0 Y0 Z0');
    console.log('G1 X5 Y5 Z-5'); // Move off of the switches for tool changes
  } else {
    console.log('G1 X-5 Y-5 Z5');
  }
})

process.stdin.resume();


```

**Comment by em** [comment]
Oh, you actually need to update package.json w/ latest gcanvas to get the non negative Z.

Then your example with --depth=-5 would be --depth=5
